=== 15563861163/Jagornet-redis/DHCPv6/src/com/agr/dhcpv6/server/dhcpServerConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Greg Rabil (INS) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
           jaxb:extensionBindingPrefixes="xjc"
           jaxb:version="2.0"
		   elementFormDefault="qualified" 
		   attributeFormDefault="unqualified">

    <xs:annotation>
       <xs:appinfo>
          <jaxb:globalBindings>
			<!-- need all generated classes to be Serializable
				 for use with Wicket -->
           <xjc:superInterface name="java.io.Serializable"/>
          </jaxb:globalBindings>
       </xs:appinfo>
    </xs:annotation>
		   
	<xs:element name="dhcpV6ServerConfig">
		<xs:annotation>
			<xs:documentation>DHCPv6 Server Configuration Schema</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="abcPolicy" type="abcPolicy"/>
				<xs:element name="xyzPolicy" type="xyzPolicy" minOccurs="0"/>
				<xs:element name="sendRequestedOptionsOnlyPolicy" type="sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
				<xs:element name="genericPolicies" type="policy" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="serverIdOption" type="serverIdOption"/>
				<xs:element name="preferenceOption" type="preferenceOption" minOccurs="0"/>
				<xs:element name="serverUnicastOption" type="serverUnicastOption" minOccurs="0"/>
				<xs:element name="statusCodeOption" type="statusCodeOption" minOccurs="0"/>
				<xs:element name="vendorInfoOption" type="vendorInfoOption" minOccurs="0"/>
				<xs:element name="dnsServersOption" type="dnsServersOption" minOccurs="0"/>
				<xs:element name="domainSearchListOption" type="domainSearchListOption" minOccurs="0"/>
				<xs:element name="sipServerAddressesOption" type="sipServerAddressesOption" minOccurs="0"/>
				<xs:element name="sipServerDomainNamesOption" type="sipServerDomainNamesOption" minOccurs="0"/>
				<xs:element name="nisServersOption" type="nisServersOption" minOccurs="0"/>
				<xs:element name="nisDomainNameOption" type="nisDomainNameOption" minOccurs="0"/>
				<xs:element name="nisPlusServersOption" type="nisPlusServersOption" minOccurs="0"/>
				<xs:element name="nisPlusDomainNameOption" type="nisPlusDomainNameOption" minOccurs="0"/>
				<xs:element name="sntpServersOption" type="sntpServersOption" minOccurs="0"/>
				<xs:element name="infoRefreshTimeOption" type="infoRefreshTimeOption" minOccurs="0"/>
				<xs:element name="genericOptions" type="option" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="filters" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="name"/>
							<xs:element name="optionExpressions" type="optionExpression" maxOccurs="unbounded"/>
							<xs:element name="abcPolicy" type="abcPolicy" minOccurs="0"/>
							<xs:element name="xyzPolicy" type="xyzPolicy" minOccurs="0"/>
							<xs:element name="sendRequestedOptionsOnlyPolicy" type="sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
							<xs:element name="genericPolicies" type="policy" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="preferenceOption" type="preferenceOption" minOccurs="0"/>
							<xs:element name="serverUnicastOption" type="serverUnicastOption" minOccurs="0"/>
							<xs:element name="statusCodeOption" type="statusCodeOption" minOccurs="0"/>
							<xs:element name="vendorInfoOption" type="vendorInfoOption" minOccurs="0"/>
							<xs:element name="dnsServersOption" type="dnsServersOption" minOccurs="0"/>
							<xs:element name="domainSearchListOption" type="domainSearchListOption" minOccurs="0"/>
							<xs:element name="sipServerAddressesOption" type="sipServerAddressesOption" minOccurs="0"/>
							<xs:element name="sipServerDomainNamesOption" type="sipServerDomainNamesOption" minOccurs="0"/>
							<xs:element name="nisServersOption" type="nisServersOption" minOccurs="0"/>
							<xs:element name="nisDomainNameOption" type="nisDomainNameOption" minOccurs="0"/>
							<xs:element name="nisPlusServersOption" type="nisPlusServersOption" minOccurs="0"/>
							<xs:element name="nisPlusDomainNameOption" type="nisPlusDomainNameOption" minOccurs="0"/>
							<xs:element name="sntpServersOption" type="sntpServersOption" minOccurs="0"/>
							<xs:element name="infoRefreshTimeOption" type="infoRefreshTimeOption" minOccurs="0"/>
							<xs:element name="genericOptions" type="option" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="links" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="name"/>
							<xs:element name="address" type="xs:string"/>
							<xs:element name="abcPolicy" type="abcPolicy" minOccurs="0"/>
							<xs:element name="xyzPolicy" type="xyzPolicy" minOccurs="0"/>
							<xs:element name="sendRequestedOptionsOnlyPolicy" type="sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
							<xs:element name="genericPolicies" type="policy" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="serverIdOption" type="serverIdOption" minOccurs="0"/>
							<xs:element name="preferenceOption" type="preferenceOption" minOccurs="0"/>
							<xs:element name="serverUnicastOption" type="serverUnicastOption" minOccurs="0"/>
							<xs:element name="statusCodeOption" type="statusCodeOption" minOccurs="0"/>
							<xs:element name="vendorInfoOption" type="vendorInfoOption" minOccurs="0"/>
							<xs:element name="dnsServersOption" type="dnsServersOption" minOccurs="0"/>
							<xs:element name="domainSearchListOption" type="domainSearchListOption" minOccurs="0"/>
							<xs:element name="sipServerAddressesOption" type="sipServerAddressesOption" minOccurs="0"/>
							<xs:element name="sipServerDomainNamesOption" type="sipServerDomainNamesOption" minOccurs="0"/>
							<xs:element name="nisServersOption" type="nisServersOption" minOccurs="0"/>
							<xs:element name="nisDomainNameOption" type="nisDomainNameOption" minOccurs="0"/>
							<xs:element name="nisPlusServersOption" type="nisPlusServersOption" minOccurs="0"/>
							<xs:element name="nisPlusDomainNameOption" type="nisPlusDomainNameOption" minOccurs="0"/>
							<xs:element name="sntpServersOption" type="sntpServersOption" minOccurs="0"/>
							<xs:element name="infoRefreshTimeOption" type="infoRefreshTimeOption" minOccurs="0"/>
							<xs:element name="genericOptions" type="option" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="filters" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="name"/>
										<xs:element name="optionExpressions" type="optionExpression" maxOccurs="unbounded"/>
										<xs:element name="abcPolicy" type="abcPolicy" minOccurs="0"/>
										<xs:element name="xyzPolicy" type="xyzPolicy" minOccurs="0"/>
										<xs:element name="sendRequestedOptionsOnlyPolicy" type="sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
										<xs:element name="genericPolicies" type="policy" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="preferenceOption" type="preferenceOption" minOccurs="0"/>
										<xs:element name="serverUnicastOption" type="serverUnicastOption" minOccurs="0"/>
										<xs:element name="statusCodeOption" type="statusCodeOption" minOccurs="0"/>
										<xs:element name="vendorInfoOption" type="vendorInfoOption" minOccurs="0"/>
										<xs:element name="dnsServersOption" type="dnsServersOption" minOccurs="0"/>
										<xs:element name="domainSearchListOption" type="domainSearchListOption" minOccurs="0"/>
										<xs:element name="sipServerAddressesOption" type="sipServerAddressesOption" minOccurs="0"/>
										<xs:element name="sipServerDomainNamesOption" type="sipServerDomainNamesOption" minOccurs="0"/>
										<xs:element name="nisServersOption" type="nisServersOption" minOccurs="0"/>
										<xs:element name="nisDomainNameOption" type="nisDomainNameOption" minOccurs="0"/>
										<xs:element name="nisPlusServersOption" type="nisPlusServersOption" minOccurs="0"/>
										<xs:element name="nisPlusDomainNameOption" type="nisPlusDomainNameOption" minOccurs="0"/>
										<xs:element name="sntpServersOption" type="sntpServersOption" minOccurs="0"/>
										<xs:element name="infoRefreshTimeOption" type="infoRefreshTimeOption" minOccurs="0"/>
										<xs:element name="genericOptions" type="option" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="link">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="name">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="value">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="policy">
		<xs:annotation>
			<xs:documentation>Generic Policy</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="name"/>
			<xs:element name="value" type="value"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="abcPolicy">
		<xs:annotation>
			<xs:documentation>Special architected ABC policy</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<xs:simpleType name="xyzPolicy">
		<xs:annotation>
			<xs:documentation>Special architected XYZ policy</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="sendRequestedOptionsOnlyPolicy">
		<xs:annotation>
			<xs:documentation>Send reply messages that contain only the options requested by the client in the ORO option, if such options are configured.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<xs:simpleType name="code">
		<xs:restriction base="xs:short"/>
	</xs:simpleType>
	<xs:simpleType name="length">
		<xs:restriction base="xs:short"/>
	</xs:simpleType>
	<xs:complexType name="opaqueData">
		<xs:choice>
			<xs:element name="asciiValue" type="xs:string"/>
			<xs:element name="hexValue" type="xs:hexBinary"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="option">
		<xs:annotation>
			<xs:documentation>Generic Option</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="code" type="code"/>
			<xs:element name="data" type="opaqueData"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="offset">
		<xs:restriction base="xs:short"/>
	</xs:simpleType>
	<xs:simpleType name="operator">
		<xs:restriction base="xs:string">
			<xs:enumeration value="equals"/>
			<xs:enumeration value="startsWith"/>
			<xs:enumeration value="endsWith"/>
			<xs:enumeration value="contains"/>
			<xs:enumeration value="regExp"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="enterpriseNumber">
		<xs:restriction base="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="ipAddress">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="domainName">
		<xs:restriction base="xs:string">
			<!-- A domain name cannot be more than 63 characters 
				 see RFC1035 Section 3.1... but a full domain name
				 can be 255, so we may need a FQDN type in addition -->
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="optionExpression">
		<xs:complexContent>
			<xs:extension base="option">
<!--
				<xs:sequence>
					<xs:element name="offset" type="offset" minOccurs="0"/>
					<xs:element name="length" type="length" minOccurs="0"/>
				</xs:sequence>
-->
				<xs:attribute name="operator" type="operator" default="equals"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="clientIdOption">
		<xs:complexContent>
			<xs:extension base="opaqueData">
				<xs:attribute name="code" type="code" fixed="1"/>
				<xs:attribute name="name" type="name" fixed="Client Identifier"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="serverIdOption">
		<xs:complexContent>
			<xs:extension base="opaqueData">
				<xs:attribute name="code" type="code" fixed="2"/>
				<xs:attribute name="name" type="name" fixed="Server Identifier"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="optionRequestOption">
		<xs:sequence>
			<xs:element name="requestedOptionCodes" type="xs:short" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="6"/>
		<xs:attribute name="name" type="name" fixed="Option Request"/>
	</xs:complexType>
	<xs:complexType name="preferenceOption">
		<xs:simpleContent>
			<xs:extension base="xs:byte">
				<xs:attribute name="code" type="code" fixed="7"/>
				<xs:attribute name="name" type="name" fixed="Preference"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="elapsedTimeOption">
		<xs:simpleContent>
			<xs:extension base="xs:short">
				<xs:attribute name="code" type="code" fixed="8"/>
				<xs:attribute name="name" type="name" fixed="Elapsed Time"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="serverUnicastOption">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="code" type="code" fixed="12"/>
				<xs:attribute name="name" type="name" fixed="Server Unicast"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="statusCodeOption">
		<xs:sequence>
			<xs:element name="statusCode" type="code"/>
			<xs:element name="message" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="13"/>
		<xs:attribute name="name" type="name" fixed="Status Code"/>
	</xs:complexType>
	<xs:complexType name="userClassOption">
		<xs:sequence>
			<xs:element name="userClasses" type="opaqueData" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="15"/>
		<xs:attribute name="name" type="name" fixed="User Class"/>
	</xs:complexType>
	<xs:complexType name="vendorClassOption">
		<xs:sequence>
			<xs:element name="enterpriseNumber" type="enterpriseNumber"/>
			<xs:element name="vendorClasses" type="opaqueData" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="16"/>
		<xs:attribute name="name" type="name" fixed="Vendor Class"/>
	</xs:complexType>
	<xs:complexType name="vendorInfoOption">
		<xs:sequence>
			<xs:element name="enterpriseNumber" type="enterpriseNumber"/>
			<xs:element name="suboptions" type="option" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="17"/>
		<xs:attribute name="name" type="name" fixed="Vendor-specific Information"/>
	</xs:complexType>
	<xs:complexType name="interfaceIdOption">
		<xs:complexContent>
			<xs:extension base="opaqueData">
				<xs:attribute name="code" type="code" fixed="18"/>
				<xs:attribute name="name" type="name" fixed="Interface ID"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="sipServerDomainNamesOption">
		<xs:sequence>
			<xs:element name="domainNames" type="domainName" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="21"/>
		<xs:attribute name="name" type="name" fixed="SIP Server Domain Names"/>
	</xs:complexType>
	<xs:complexType name="sipServerAddressesOption">
		<xs:sequence>
			<xs:element name="serverIpAddresses" type="ipAddress" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="22"/>
		<xs:attribute name="name" type="name" fixed="SIP Server Addresses"/>
	</xs:complexType>
	<xs:complexType name="dnsServersOption">
		<xs:sequence>
			<xs:element name="serverIpAddresses" type="ipAddress" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="23"/>
		<xs:attribute name="name" type="name" fixed="DNS Recursive Name Server"/>
	</xs:complexType>
	<xs:complexType name="domainSearchListOption">
		<xs:sequence>
			<xs:element name="domainNames" type="domainName" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="24"/>
		<xs:attribute name="name" type="name" fixed="Domain Search List"/>
	</xs:complexType>
	<xs:complexType name="nisServersOption">
		<xs:sequence>
			<xs:element name="serverIpAddresses" type="ipAddress" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="27"/>
		<xs:attribute name="name" type="name" fixed="Network Information Service (NIS) Servers"/>
	</xs:complexType>
	<xs:complexType name="nisPlusServersOption">
		<xs:sequence>
			<xs:element name="serverIpAddresses" type="ipAddress" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="28"/>
		<xs:attribute name="name" type="name" fixed="Network Information Service V2 (NIS+) Servers"/>
	</xs:complexType>
	<xs:complexType name="nisDomainNameOption">
		<xs:sequence>
			<xs:element name="domainName" type="domainName"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="29"/>
		<xs:attribute name="name" type="name" fixed="Network Information Service (NIS) Domain Name"/>
	</xs:complexType>
	<xs:complexType name="nisPlusDomainNameOption">
		<xs:sequence>
			<xs:element name="domainName" type="domainName"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="30"/>
		<xs:attribute name="name" type="name" fixed="Network Information Service V2 (NIS+) Domain Name"/>
	</xs:complexType>
	<xs:complexType name="sntpServersOption">
		<xs:sequence>
			<xs:element name="serverIpAddresses" type="ipAddress" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="code" type="code" fixed="31"/>
		<xs:attribute name="name" type="name" fixed="Simple Network Time Protocol (SNTP) Servers"/>
	</xs:complexType>
	<xs:complexType name="infoRefreshTimeOption">
		<xs:simpleContent>
			<xs:extension base="xs:int">
				<xs:attribute name="code" type="code" fixed="32"/>
				<xs:attribute name="name" type="name" fixed="Information Refresh Time"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

<!-- Consider using these types	
     <simpleType name="dotQuadIPv4Type">
       <restriction base="string">
         <pattern value="([\d]{1,3}.){3}[\d]{1,3}" />
         <minLength value="7" />
         <maxLength value="15" />
       </restriction>
     </simpleType>

     ** does not support '::' **
     <simpleType name="textIPv6AddressType">
       <restriction base="string">
         <pattern value="(([\dA-Fa-f]{1,4}:){7}[\dA-Fa-f]{1,4})(:([\d]{1,3}.){3}[\d]{1,3})?"/>
         <minLength value="16"/>
         <maxLength value="39"/>
       </restriction>
     </simpleType>

     <simpleType name="domainNameType">
       <restriction base="token">
         <pattern
           value="([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]\.)*([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])?" />
         <maxLength value="255" />
       </restriction>
     </simpleType>
-->	
	
</xs:schema>

=== 15563861163/Jagornet-redis/DHCPv6/src/com/jagornet/dhcpv6/server/dhcpServerConfig2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="dhcpServerConfig.xsl"?>
<dhcpV6ServerConfig 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="dhcpServerConfig.xsd">
	
	<abcPolicy>true</abcPolicy>
	<serverIdOption>
		<hexValue>abcdef0123456789</hexValue>
	</serverIdOption>
	<dnsServersOption>
		<serverIpAddresses>3ffe::0001</serverIpAddresses>
		<serverIpAddresses>3ffe::0002</serverIpAddresses>
		<serverIpAddresses>3ffe::0003</serverIpAddresses>
	</dnsServersOption>
	<domainListOption>
		<domainNames>foo.com.</domainNames>
		<domainNames>bar.com.</domainNames>
		<domainNames>yuk.com.</domainNames>
	</domainListOption>
	<filterGroups>
		<name>UserClass Filter Group 1</name>
		<optionExpressions>
			<code>15</code>
			<data>
				<asciiValue>FilterUserClass</asciiValue>
			</data>
		</optionExpressions>
		<domainListOption>
			<domainNames>filter.com.</domainNames>
		</domainListOption>
	</filterGroups>
</dhcpV6ServerConfig>
